<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Spin_the_game</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>aefb655c-3959-490b-9b34-06749a56d15d</testSuiteGuid>
   <testCaseLink>
      <guid>2b316fbf-f8eb-4655-9e25-a7fba75d4d4a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>370a2f99-e124-4079-80b6-f9162b6bd13c</id>
         <iterationEntity>
            <iterationType>SPECIFIC</iterationType>
            <value>1,3</value>
         </iterationEntity>
         <testDataId>Data Files/STG_data</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f77b8a4a-f8a9-467b-98b1-6d99cfc3449a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7195aa57-3a15-48ec-8613-d04a805f8e7d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e22b8aa1-c5d6-4b3b-ac4c-da2c7a72e1a3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>24d65cbb-4d3d-40b6-a1a1-a6e95283f0bf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1d12dd1e-f8a6-4b30-9152-345307cac30c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d2db140a-d8b9-451e-af80-44ae716f146a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>32ebf6d0-9764-4087-ad4a-ab3a404d971d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Spin</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>f41f3801-57fb-4fa7-9ccd-85e527b68680</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/STG_data</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>71779572-8a36-4263-9c89-af62b92d798e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>55f3eace-53ac-4487-8ae5-d88009684bd9</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
